### PR TITLE
Update password decryption

### LINKED ISSUE #92: GitHub Personal Access token getting invalidated
we are using this plugin along with the Github Organization jobs to accomplish automated PR builds.

the issue we are having is that somewhere in the communication with this configuration the Github PATs is getting invalidated.
we have a simple service account with a PAT token on Github Enterprise set up for processing Pull requests.

periodically when trying to upload coverage reports 
```
[GitHub PR Status] start
[GitHub PR Status] getting master coverage...
use default coverage repo
```
results in
``` 
GitHub has been notified of this commit’s build result

java.io.IOException: Server returned HTTP response code: 401 for URL: https://github.digitalglobe.com/api/v3/user
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:69)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:400)
Caused: java.io.IOException: Server returned HTTP response code: 401 for URL: https://github.digitalglobe.com/api/v3/user
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:197)
	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:326)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:91)
	at org.kohsuke.github.GitHubClient.lambda$fetch$0(GitHubClient.java:145)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:461)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:412)
Caused: org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/enterprise/2.22/rest"}
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:495)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:420)
	at org.kohsuke.github.GitHubClient.fetch(GitHubClient.java:145)
	at org.kohsuke.github.GitHubClient.<init>(GitHubClient.java:134)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.<init>(GitHubHttpUrlConnectionClient.java:45)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:115)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:423)
	at org.kohsuke.github.GitHub.connectToEnterpriseWithOAuth(GitHub.java:178)
	at org.kohsuke.github.GitHub.connectToEnterprise(GitHub.java:157)
	at com.github.terma.jenkins.githubprcoveragestatus.GitHubPullRequestRepository.getGitHub(GitHubPullRequestRepository.java:68)
	at com.github.terma.jenkins.githubprcoveragestatus.GitHubPullRequestRepository.getGitHubRepository(GitHubPullRequestRepository.java:39)
	at com.github.terma.jenkins.githubprcoveragestatus.CompareCoverageAction.perform(CompareCoverageAction.java:137)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

The Declaritive pipeline looks like this

```
        stage('PR Coverage to Github') {
            when { allOf {not { branch 'master' }; expression { return env.CHANGE_ID != null }} }
            steps {
                script {
                    currentBuild.result = 'SUCCESS'
                 }
                step([$class: 'CompareCoverageAction',
                              publishResultAs: 'statusCheck',
                              scmVars: [GIT_URL: '$GIT_URL']])
            }
        }
```

Digging around Github logs hasnt produced anything useful as of yet.

### PR DESCRIPTION
**Pull request by adnancerner**
Number of the dependencies are out of date which causes latest Jenkins to be unstable with this plugin as the method for fetching the settings from Jenkins configuration is different. This should address issues with corrupted personal access token.

Fixes #92

### CODE REVIEW

**Review by tburow — APPROVED** [review]
Good find

**Review by maxr-jidol — APPROVED** [review]

**Comment by adnancerner** [comment]
Turns out Jenkins could not handle the secret so the encrypted value was being used instead of the actual value. So if you don't intentionally edit it the password config loads the encrypted value. So used Secret util to decrypt the value. I believe this should fix the error, tested locally.

To reproduce:
make any change that is not the PAT, then you'll see the PAT has been overwritten with the encrypted version.

Conclusion:
So just need to decrypt it.

**Review by tburow — APPROVED** [review]

**Comment by harrysingh** [comment]
Whats the plan to release this?

**Comment by cosminrentea** [comment]
also interested

**Comment by bhellema** [comment]
@tburow - is this project dead? What's holding this PR up from being merged?

**Comment by tburow** [comment]
> @tburow - is this project dead? What's holding this PR up from being merged?

yes this project is dead.  I was told to migrate to the Github checks API

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
