### PR TITLE
[INFRA-1851] Enable tlsv1.2 support

### PR DESCRIPTION
**Pull request by olblak**
This PR is an attempt to fix:
```
08:49:17 [linux-7] [ERROR]     Non-resolvable parent POM for org.jenkins-ci.plugins:github-pr-coverage-status:1.10.1-SNAPSHOT: Could not transfer artifact org.jenkins-ci.plugins:plugin:pom:2.11 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): Received fatal alert: protocol_version and 'parent.relativePath' points at no local POM @ line 3, column 13 -> [Help 2]
08:49:17 [linux-7] org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact org.jenkins-ci.plugins:plugin:pom:2.11 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): Received fatal alert: protocol_version
```

https://repo.jenkins-ci.org only support TLSv1.2

### CODE REVIEW

**Comment by dmotpan** [comment]
@olblak I figured out that if the build runs on Java 8 only, then it passes (see 2e1c48097c65d322d767abbf43bf64de1483adfb). Should it be used as a solution to fix the build?

**Comment by olblak** [comment]
If you don't need java7 then definitely you can close this PR, as java 8 works with TLSv1.2 by default

**Comment by dmotpan** [comment]
@olblak I bumped up the java version to 8 for now as there's no reply

**Comment by terma** [comment]
@dmotpan I think Java 8 is fine, as all modern version of Jenkins requires at least Java 8, for those who need old support, can create an issue or use an old version of plugins.

**Pull request closed without merging**
